### ISSUE TITLE
Indexing stopped on around Sept 13, 2016

### ISSUE THREAD

**Issue by agoloprem** [GitbookIO/plugin-algolia#7]
Hi,

Our GitBook, https://agolo.gitbooks.io/wiki/, stopped updating the Algolia index around 8 days ago. That would be around Sept 13. [Here is a screenshot of the Algolia "Latest operations" list.](http://imgur.com/a/Pynm5)

We didn't change any Gitbook settings on Sept 13. Our environment variable for the Admin key is still set correctly. However, at the bottom of each change's build log, we see the following message:

```
warn: Algolia indexation is disabled: 
warn: You need to configure the ALGOLIA_PRIVATEKEY environment variable using your Admin API Key. 
```

Our `book.json` has the following attributes:

``` json
{
    "plugins": [
        "simple-page-toc",
        "edit-link",
        "page-toc",
        "algolia",
        "mathjax"
    ],
    "pluginsConfig": {
        "edit-link": {
            "base": "https://www.gitbook.com/book/agolo/wiki/edit#/edit/master/",
            "label": "Edit This Page"
        },
        "page-toc": {
            "selector": ".markdown-section h1, .markdown-section h2, .markdown-section h3",
            "position": "top"
        },
        "algolia": {
            "index": "Agolo_Gitbook",
            "applicationID": "OUR APP ID",
            "publicKey": "OUR PUBLIC KEY",
            "freeAccount": "true"
        }
    }
}
```

We are on the free tier of Algolia, and today is the end of our first month on this plan.

Thanks for your help!

**Comment by agoloprem** [comment]
Hi, this is blocking our ability to migrate our company's old internal knowledge base wiki to Gitbook. Our old knowledge base is too large for us to use `lunr.js`, which is why we need Algolia.

**Comment by Soreine** [comment]
Hello, @agoloprem, have you made sure that you added an environment variable to your book's settings, named `ALGOLIA_PRIVATEKEY`, with the value of your private Algolia key?

Since this is probably not related with the plugin itself, I close this issue. Feel free to send me an email at `nicolas(at)gitbook.com`.
