### ISSUE TITLE
Close search results

### ISSUE THREAD

**Issue by timdorr** [GitbookIO/plugin-algolia#9]
There is no way (that I can see) to close or hide the search results if you are done with them. Right now, the only way I can see to do that is backspace all the way back to the beginning of your search terms or to navigate to another page. A "X" icon or ESC key handler would be good to remove them without having to whack your keyboard a bunch of times or change pages and lose your place.

**Comment by Soreine** [comment]
This should be fixed in the upcoming GitBook version 4
